export const ActionTypes = {
    SET_USER: "SET_USER",
    SET_EVENT: "SET_EVENT",
    SET_EVENTS: "SET_EVENTS",
    SET_CATEGORY: "SET_CATEGORY",
    SET_LOCATIONS: "SET_LOCATIONS",
    SELECTED_EVENT: "SELECTED_EVENT",
    REMOVE_EVENT: "REMOVE_EVENT",

}